---
name: 🐞 Bug 报告
about: 提交一个 Bug 报告，以帮助我们改进项目
title: "[Bug] 简要描述问题"
labels: bug
assignees: ''

---

### 🐞 Bug 描述

简洁明了地描述你遇到的问题。

> 示例：“点击登录按钮无响应，控制台报错 `TypeError: xxx`。”

---

### ✅ 复现步骤

请提供复现该问题的详细步骤：

1. 进入页面 '...'
2. 点击 '...'
3. 滚动到 '...'
4. 发现问题 '...'

---

### 🧩 预期行为

请描述你原本期望看到的正确结果。

---

### 📸 截图（可选）

如果适用，请附上截图以帮助我们理解问题。

---

### 💻 运行环境

请填写与问题相关的环境信息：

- 操作系统：如 Windows 10 / macOS 14 / Ubuntu 22.04
- 浏览器或平台：如 Chrome 124 / Electron / Node.js 版本
- 项目版本或 Git 分支：如 `dev` 分支，commit `abc1234`

---

### 📋 补充信息（可选）

如有更多补充信息，请在此提供。

---

